### ISSUE TITLE
Getting attached error  

### ISSUE THREAD

**Issue by pratikibm** [hudeldudel/postman-exporter#11]
@hudeldudel I am getting Below error in debug mode I am passing collection.json & environment.json file.could please look at if you can trace this error.

{"message":"timings completed 1609411150464","level":"debug","timestamp":"2020-12-31T10:39:10.504Z"}
/mnt/c/Users/pratik.shindeGetting belo/Desktop/grafanatest/postman-expoter/postman-exporter-0.1.0/postman-exporter-0.1.0/prober/prober.js:99
            for (const [key2, assertion] of Object.entries(execution.assertions)) {
                                                   ^

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at EventEmitter.newman.run.on.on (/mnt/c/Users/pratik.shinde/Desktop/grafanatest/postman-expoter/postman-exporter-0.1.0/postman-exporter-0.1.0/prober/prober.js:99:52)
    at EventEmitter.emit (/mnt/c/Users/pratik.shinde/Desktop/grafanatest/postman-expoter/postman-exporter-0.1.0/postman-exporter-0.1.0/node_modules/eventemitter3/index.js:203:33)
    at /mnt/c/Users/pratik.shinde/Desktop/grafanatest/postman-expoter/postman-exporter-0.1.0/postman-exporter-0.1.0/node_modules/newman/lib/run/index.js:328:33
    at wrapper (/mnt/c/Users/pratik.shinde/Desktop/grafanatest/postman-expoter/postman-exporter-0.1.0/postman-exporter-0.1.0/node_modules/async/internal/once.js:12:16)
    at eachOfArrayLike (/mnt/c/Users/pratik.shinde/Desktop/grafanatest/postman-expoter/postman-exporter-0.1.0/postman-exporter-0.1.0/node_modules/async/eachOf.js:45:9)
    at eachOf (/mnt/c/Users/pratik.shinde/Desktop/grafanatest/postman-expoter/postman-exporter-0.1.0/postman-exporter-0.1.0/node_modules/async/eachOf.js:112:12)
    at awaitable (/mnt/c/Users/pratik.shinde/Desktop/grafanatest/postman-expoter/postman-exporter-0.1.0/postman-exporter-0.1.0/node_modules/async/internal/awaitify.js:13:28)
    at eachLimit (/mnt/c/Users/pratik.shinde/Desktop/grafanatest/postman-expoter/postman-exporter-0.1.0/postman-exporter-0.1.0/node_modules/async/each.js:84:31)
    at awaitable (/mnt/c/Users/pratik.shinde/Desktop/grafanatest/postman-expoter/postman-exporter-0.1.0/postman-exporter-0.1.0/node_modules/async/internal/awaitify.js:13:28)
    at done (/mnt/c/Users/pratik.shinde/Desktop/grafanatest/postman-expoter/postman-exporter-0.1.0/postman-exporter-0.1.0/node_modules/newman/lib/run/index.js:326:21)
    at /mnt/c/Users/pratik.shinde/Desktop/grafanatest/postman-expoter/postman-exporter-0.1.0/postman-exporter-0.1.0/node_modules/postman-runtime/lib/backpack/index.js:58:34
    at PostmanCollectionRun._process (/mnt/c/Users/pratik.shinde/Desktop/grafanatest/postman-expoter/postman-exporter-0.1.0/postman-exporter-0.1.0/node_modules/postman-runtime/lib/runner/run.js:163:13)
    at PostmanCollectionRun.<anonymous> (/mnt/c/Users/pratik.shinde/Desktop/grafanatest/postman-expoter/postman-exporter-0.1.0/postman-exporter-0.1.0/node_modules/postman-runtime/lib/runner/run.js:169:76)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! postman-exporter@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the postman-exporter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by hudeldudel** [comment]
I'm quite sure this has already been fixed with #10 

Can you please try with current trunk.

I will also create a new release the next days.

**Comment by pratikibm** [comment]
This has been resolved thanks!!
